'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, Sparkles } from 'lucide-react';

export default function OnboardingPage(){
 const [sent,setSent]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const subject=encodeURIComponent('New Ava Customer Onboarding - '+String(f.get('business')));const body=encodeURIComponent(`Business: ${f.get('business')}\nContact: ${f.get('contact')}\nPhone: ${f.get('phone')}\nEmail: ${f.get('email')}\nIndustry: ${f.get('industry')}\nHours: ${f.get('hours')}\nServices: ${f.get('services')}\nVoice preference: ${f.get('voice')}\nCall instructions / FAQs: ${f.get('instructions')}`);window.location.href=`mailto:colecollins763@gmail.com?subject=${subject}&body=${body}`;setSent(true)}
 return <main className="onboard"><nav><Link href="/"><Sparkles/> Workforce AI</Link></nav><section><div className="success"><CheckCircle2/><div><span>PAYMENT COMPLETE</span><h1>Now let's build your receptionist.</h1><p>Send us the basics below. We'll use this to configure Ava around your business and contact you to finish voice and call-flow setup.</p></div></div><form onSubmit={submit}><div className="two"><label>Business name<input name="business" required/></label><label>Your name<input name="contact" required/></label></div><div className="two"><label>Best phone<input name="phone" required/></label><label>Email<input name="email" type="email" required/></label></div><label>Industry / business type<input name="industry" required/></label><label>Business hours<input name="hours" placeholder="Mon–Fri 7am–5pm; emergency calls after hours"/></label><label>Services Ava should know<textarea name="services" rows={4} placeholder="List your main services, service area, estimate process, etc."/></label><label>Voice preference<select name="voice"><option>Help me choose a professional voice</option><option>Friendly female voice</option><option>Friendly male voice</option><option>Professional / polished</option><option>Warm / conversational</option><option>Explore using my own voice</option></select></label><label>Important questions, FAQs & call instructions<textarea name="instructions" rows={6} placeholder="What should Ava ask? What should she never promise? When should a caller be escalated?"/></label><button type="submit">Send My Setup Information</button>{sent&&<small>Your email app should open with the onboarding details ready to send.</small>}</form></section><style jsx>{`
.onboard{min-height:100vh;background:#07110c;color:#f6f8f5;font-family:Inter,system-ui,sans-serif;padding-bottom:80px}.onboard nav{height:70px;border-bottom:1px solid #173126;display:flex;align-items:center;padding:0 max(20px,calc((100vw - 820px)/2))}.onboard nav a{color:inherit;text-decoration:none;display:flex;gap:8px;align-items:center;font-weight:850}.onboard nav svg{color:#8fe66f}.onboard section{width:min(820px,calc(100% - 40px));margin:65px auto}.success{display:flex;gap:20px;align-items:flex-start;margin-bottom:35px}.success>svg{width:52px;height:52px;color:#8fe66f;flex:none}.success span{color:#8fe66f;font-size:10px;font-weight:900;letter-spacing:.13em}.success h1{font:600 clamp(40px,5vw,58px)/1.05 Georgia,serif;margin:8px 0 12px}.success p{color:#9ba8a0;line-height:1.6}.onboard form{background:#0d1c13;border:1px solid #294536;border-radius:18px;padding:30px;display:grid;gap:16px}.onboard label{display:grid;gap:7px;color:#b9c3bd;font-size:11px;font-weight:800}.onboard input,.onboard textarea,.onboard select{width:100%;background:#f8faf7;color:#102017;border:0;border-radius:8px;padding:13px;font:inherit}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.onboard button{border:0;background:#8fe66f;color:#07110c;border-radius:9px;padding:14px;font-weight:900;cursor:pointer}.onboard form small{text-align:center;color:#8fe66f}@media(max-width:620px){.two{grid-template-columns:1fr}.onboard form{padding:20px}.success{display:block}.success>svg{margin-bottom:15px}}
`}</style></main>
}
