'use client';
import { useMemo, useState } from 'react';
import { ArrowRight, Bot, CalendarCheck, Check, Home, Mail, MessageSquare, Phone, Search, Sparkles, Target, WandSparkles } from 'lucide-react';

const agents = [
  ['Lead Machine', 'Find and qualify prospects automatically', Search],
  ['AI Receptionist', 'Answer, qualify and route calls 24/7', Phone],
  ['Follow-Up Machine', 'Keep leads moving until they book', MessageSquare],
  ['Neighborhood Canvasser', 'Find properties and create personalized offers', Home],
  ['Marketing Department', 'Create campaigns, content and landing pages', Target],
  ['Custom AI Employee', 'Describe a repetitive job. We build the workflow.', Bot],
];
const workflow = [
  ['1', 'Find opportunity', 'Identify properties or prospects that fit your rules.'],
  ['2', 'Create the vision', 'AI generates realistic Clean, Upgraded and Premium concepts.'],
  ['3', 'Build the takeoff', 'Match the concept to supplier products, quantities and material costs.'],
  ['4', 'Price for profit', 'Apply your labor, overhead and target gross margin.'],
  ['5', 'Personalize outreach', 'Create a postcard + QR landing page showing that exact transformation.'],
  ['6', 'Convert the lead', 'Capture interest, follow up, book the estimate and track the opportunity.'],
];
const materials = [['Dwarf Boxwood',7,34.98],['Hydrangea',4,36.98],['Seasonal color',8,9.98],['Black mulch',16,4.98],['Landscape edging',65,1.42]];

export default function HomePage() {
  const [margin,setMargin]=useState(40);
  const [labor,setLabor]=useState(1150);
  const [postcode,setPostcode]=useState('35077');
  const qrUrl=`https://workforce.vercel.app/property/${postcode}`;
  const materialCost=useMemo(()=>materials.reduce((s,[,q,p])=>s+Number(q)*Number(p),0),[]);
  const cost=materialCost+labor+208;
  const sell=cost/(1-margin/100);
  return <main>
    <nav className="nav"><a className="brand" href="#"><span className="logo"><Sparkles size={18}/></span> Workforce<span>AI</span></a><div className="navlinks"><a href="#workforce">AI Workforce</a><a href="#canvasser">Property AI</a><a href="#pricing">Pricing</a></div><a className="button small" href="#audit">Start Free AI Audit</a></nav>
    <section className="hero wrap"><div className="eyebrow"><span>●</span> AI EMPLOYEES BUILT AROUND YOUR BUSINESS</div><h1>Stop doing work<br/>AI can do <em>for you.</em></h1><p className="lede">Tell us what you want your business to accomplish. We build an AI workforce to find leads, answer customers, follow up, book jobs and automate the repetitive work behind growth.</p><div className="actions"><a className="button" href="#audit">Find What AI Can Do For My Business <ArrowRight size={18}/></a><a className="ghost" href="#canvasser">See the property demo</a></div><div className="proof"><span><Check/> Built for outcomes, not tech</span><span><Check/> You approve sensitive actions</span><span><Check/> Start with a paid pilot</span></div></section>
    <section className="metrics wrap"><div><b>147</b><span>prospects analyzed</span></div><div><b>26</b><span>qualified opportunities</span></div><div><b>7</b><span>conversations started</span></div><div><b>$18.42</b><span>automation spend</span></div><div className="accent"><b>$4,850</b><span>demo pipeline created</span></div></section>
    <section id="workforce" className="section wrap"><div className="sectionhead"><span>YOUR AI WORKFORCE</span><h2>Give AI a job. Not another tool.</h2><p>Choose a proven employee or tell us what repetitive work is costing you time and money.</p></div><div className="cards">{agents.map(([name,desc,Icon]:any)=><article className="card" key={name}><div className="icon"><Icon size={22}/></div><h3>{name}</h3><p>{desc}</p><button>View workflow <ArrowRight size={15}/></button></article>)}</div></section>
    <section id="canvasser" className="dark"><div className="wrap"><div className="tag">FEATURED WORKFORCE</div><div className="split intro"><div><h2>The AI Neighborhood<br/><em>Canvasser</em></h2><p>Turn a homeowner&apos;s actual property into a personalized sales opportunity—from prospect discovery to a priced project concept and postcard.</p></div><div className="mini"><WandSparkles/><div><b>Designed to sell realistic work</b><span>Clean & Simple is the default. Homeowners can also explore Upgraded and Premium options.</span></div></div></div><div className="flow">{workflow.map(([n,t,d])=><div className="flowrow" key={n}><span>{n}</span><div><b>{t}</b><p>{d}</p></div></div>)}</div></div></section>
    <section className="section wrap"><div className="sectionhead left"><span>DESIGN → MATERIALS → PRICE</span><h2>A pretty rendering becomes a sellable project.</h2></div><div className="estimator"><div className="design"><div className="house"><img src="/postcard-yard.png" alt="Photorealistic current and future landscaping concept for a suburban property"/><div className="before">CURRENT</div><div className="after">FUTURE CONCEPT</div></div><div className="options"><button className="active">Clean & Simple</button><button>Upgraded</button><button>Premium</button></div><p className="notice">Demo concept. Production designs will use the property&apos;s image and connected supplier catalog.</p></div><div className="quote"><div className="qtop"><div><small>PROJECT TAKEOFF</small><h3>Materials used in this design</h3></div><span>DEMO DATA</span></div>{materials.map(([m,q,p])=><div className="line" key={String(m)}><span>{m}<small>{q} × ${Number(p).toFixed(2)}</small></span><b>${(Number(q)*Number(p)).toFixed(2)}</b></div>)}<div className="controls"><label>Estimated labor <input type="number" value={labor} onChange={e=>setLabor(Number(e.target.value))}/></label><label>Your target gross margin <div className="range"><input type="range" min="10" max="70" value={margin} onChange={e=>setMargin(Number(e.target.value))}/><b>{margin}%</b></div></label></div><div className="totals"><span>Estimated direct cost <b>${cost.toFixed(0)}</b></span><span className="recommended">Recommended selling price <b>${sell.toFixed(0)}</b></span><small>Formula: direct cost ÷ (1 − gross margin). Final pricing is always controlled by the business owner.</small></div></div></div></section>
    <section className="postcard"><div className="wrap split"><div><span className="tag light">PERSONALIZED DIRECT MAIL</span><h2>Don&apos;t tell them.<br/><em>Show them.</em></h2><p>Each prospect can receive a postcard showing a realistic concept for their property. The QR code opens their personalized page, captures the lead and starts your follow-up workflow.</p><div className="chain"><span><Mail/> Personalized postcard</span><ArrowRight/><span><Home/> Property page</span><ArrowRight/><span><CalendarCheck/> Estimate request</span></div></div><div className="postcardmock"><div className="pcphoto"><img src="/postcard-yard.png" alt="Current and future landscaping photos for a personalized postcard"/><span>Your property. Reimagined.</span></div><div className="pcbody"><div className="stamp">PROPERTY PREVIEW</div><b>We redesigned your front yard.</b><p>See a realistic idea created for your property and request a no-pressure estimate.</p><img className="qr" src={`https://api.qrserver.com/v1/create-qr-code/?size=160x160&margin=8&data=${encodeURIComponent(qrUrl)}`} alt={`Personalized QR code for postcode ${postcode}`}/><small>SCAN TO SEE YOUR TRANSFORMATION</small><label className="qrinput">Personalize postcode<input aria-label="Postcode for QR code" value={postcode} onChange={e=>setPostcode(e.target.value.replace(/[^0-9A-Za-z -]/g,'').slice(0,10))}/></label></div></div></div></section>
    <section id="audit" className="section wrap audit"><div><span className="eyebrow">FREE AI BUSINESS AUDIT</span><h2>Where is your business<br/>leaving money on the table?</h2><p>Answer a few questions. We&apos;ll identify the AI employees and automations most likely to save time or generate revenue for your business.</p></div><form onSubmit={e=>e.preventDefault()}><label>What type of business do you run?<select defaultValue=""><option value="" disabled>Select your business</option><option>Landscaping / Lawn Care</option><option>Roofing</option><option>HVAC</option><option>Plumbing</option><option>Painting</option><option>Real Estate</option><option>Other Service Business</option></select></label><label>What do you want AI to help with?<select><option>Get me more customers</option><option>Stop leads from falling through</option><option>Save me office time</option><option>Improve my marketing</option><option>Increase repeat customers</option><option>Automate my sales process</option></select></label><label>ZIP / primary service area<input placeholder="35077"/></label><button className="button">Build My AI Workforce <ArrowRight size={18}/></button><small>No obligation. This is a product demo while founding-customer automations are configured individually.</small></form></section>
    <section id="pricing" className="founding"><div className="wrap"><div className="sectionhead"><span>FOUNDING CUSTOMER PROGRAM</span><h2>We&apos;ll build your first AI employee with you.</h2><p>We&apos;re onboarding early businesses as paid pilots. You get a custom workflow configured around your business and help shape the platform.</p></div><div className="pricecard"><div><small>FOUNDING PILOT</small><h3>$299 <span>setup</span></h3><p>then $99/month for the initial managed automation</p></div><ul><li><Check/> Business automation audit</li><li><Check/> One custom AI workflow</li><li><Check/> Dashboard + outcome tracking</li><li><Check/> Human approval guardrails</li><li><Check/> Founding-customer support</li></ul><button className="button">Request a Founding Spot <ArrowRight size={18}/></button></div><p className="disclosure">We do not claim every displayed integration is live today. Paid pilots fund and prioritize the automation your business actually needs.</p></div></section>
    <footer className="wrap"><a className="brand" href="#"><span className="logo"><Sparkles size={18}/></span> Workforce<span>AI</span></a><p>AI employees built around business outcomes.</p><span>© 2026 AI Business Workforce</span></footer>
  </main>;
}
