'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, Home, Mail, QrCode, Search, Sparkles, Target, WandSparkles } from 'lucide-react';
import { FOUNDING_PAYMENT_LINK } from '@/lib/payments';

const industries = ['Landscaping','Roofing','Pressure Washing','Exterior Painting','Fencing','Tree Service','Hardscaping','Outdoor Lighting'];
const examples: Record<string,string[]> = {
  Landscaping:['6 compact evergreen shrubs','3 flowering hydrangeas','Seasonal color','Fresh mulch + bed edging'],
  Roofing:['Architectural shingles','New ridge cap','Updated roof vents','Matching flashing'],
  'Pressure Washing':['Driveway surface cleaning','Front walk cleaning','Curb treatment','Entry concrete brightening'],
  'Exterior Painting':['Updated body color','Contrasting trim','Front-door accent','Exterior prep + coating'],
  Fencing:['Privacy fence concept','Matching gate','Post + rail layout','Property-line finish'],
  'Tree Service':['Canopy thinning','Dead-limb removal','Crown shaping','Debris cleanup'],
  Hardscaping:['Paver walkway','Defined border','Decorative gravel','Planting accents'],
  'Outdoor Lighting':['Path lights','Facade uplighting','Feature-tree lighting','Entry lighting'],
};

export default function VisualCanvasserSales(){
 const [industry,setIndustry]=useState('Landscaping');
 return <main className="vc-page">
  <nav className="nav"><Link className="brand" href="/"><span className="logo"><Sparkles size={18}/></span> Workforce<span>AI</span></Link><div className="navlinks"><a href="#how">How it works</a><a href="#example">Example</a><a href="#offer">Founding offer</a></div><a className="button small" href={FOUNDING_PAYMENT_LINK}>Get My First Campaign</a></nav>
  <section className="vc-hero wrap"><div><div className="eyebrow">VISUAL CANVASSER FOR HOME-SERVICE BUSINESSES</div><h1>Don't just tell homeowners what you can do. <em>Show them.</em></h1><p className="lede">We help choose promising streets, prepare clearly labeled yard concepts, and turn the approved campaign into direct mail with a trackable estimate page.</p><div className="actions left-actions"><a className="button" href={FOUNDING_PAYMENT_LINK}>Pay $299 — Start My Campaign <ArrowRight size={18}/></a><a className="ghost" href="#example">See a campaign example</a></div><div className="proof vc-proof"><span><Check/> Managed first campaign</span><span><Check/> Built around your service</span><span><Check/> You approve before mailing</span></div></div><div className="vc-mailer"><div className="vc-mail-photo"><span>DEMO YARD CONCEPT</span><div>🏡</div><b>Imagine a fresh project here.</b></div><div className="vc-mail-copy"><small>EXAMPLE POSTCARD</small><h3>A fresh idea for your front yard.</h3><p>Scan to see the concept, what's included, and request an estimate.</p><div className="vc-qr"><QrCode size={56}/><span>PROJECT<br/>PREVIEW</span></div></div></div></section>

  <section id="how" className="section vc-soft"><div className="wrap"><div className="sectionhead"><span>FROM PROSPECT TO ESTIMATE</span><h2>A smarter version of neighborhood canvassing.</h2><p>Instead of sending the same advertisement to everyone, the managed founding campaign builds outreach around the work you actually want to sell.</p></div><div className="vc-steps">{[[Search,'1','Target','Choose service areas and the kinds of jobs you want.'],[Home,'2','Concept','Prepare a clearly labeled yard project idea for campaign review.'],[WandSparkles,'3','Explain','Show the improvements, materials and project scope represented.'],[Mail,'4','Approve','Review the postcard before anything is sent.'],[QrCode,'5','Track','A unique QR page captures interest and estimate requests.'],[Target,'6','Follow up','Interested homeowners move into your sales workflow.']].map(([Icon,n,t,d]:any)=><article key={n}><span>{n}</span><Icon size={22}/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

  <section id="example" className="section wrap"><div className="sectionhead"><span>LABELED CAMPAIGN EXAMPLE</span><h2>One campaign format. Different home-service businesses.</h2><p>Choose a service to see an illustrative concept and scope. This is not a live address lookup or automatic rendering tool.</p></div><div className="vc-tabs">{industries.map(x=><button key={x} onClick={()=>setIndustry(x)} className={industry===x?'active':''}>{x}</button>)}</div><div className="vc-demo"><div className="vc-before"><small>DEMO STARTING VIEW</small><div>🏠</div><b>Illustrative property placeholder</b><p>Production campaigns use only imagery and property data that are available and approved for use.</p></div><div className="vc-arrow"><ArrowRight/></div><div className="vc-after"><small>DEMO {industry.toUpperCase()} CONCEPT</small><div>🏡</div><b>Illustrative project direction</b><ul>{examples[industry].map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul></div><div className="vc-scope"><small>EXAMPLE QR PAGE</small><h3>A project idea for review</h3><p>A concise explanation of the proposed work, plus a direct way to request an estimate.</p><div className="vc-qr big"><QrCode size={70}/></div><a className="button" href={FOUNDING_PAYMENT_LINK}>Pay $299 — Start My Campaign</a></div></div></section>

  <section className="dark vc-difference"><div className="wrap split"><div><div className="tag">WHY THIS IS DIFFERENT</div><h2>Generic postcards advertise.<br/><em>This starts a conversation.</em></h2><p>The homeowner receives a project idea tied to the campaign you approved. When they scan, the QR page gives them a direct way to request an estimate.</p></div><div className="vc-stack"><div><b>1</b><span>Campaign-specific creative</span></div><div><b>2</b><span>Service-specific scope</span></div><div><b>3</b><span>Personalized QR destination</span></div><div><b>4</b><span>Lead capture + follow-up workflow</span></div></div></div></section>

  <section id="offer" className="section wrap vc-offer"><div><span className="eyebrow">FOUNDING CUSTOMER CAMPAIGN</span><h2>Be one of the first businesses we build this for.</h2><p>We're onboarding a small number of home-service businesses while we finish automating the complete workflow. Your first campaign is delivered as a managed service and helps shape the production product.</p><div className="vc-honesty"><b>What “founding customer” means</b><p>Some campaign steps may be completed with human-assisted AI while integrations are being finalized. We will not claim an external data source, supplier catalog, mailing integration, or property-image source is automated until it is actually connected and tested.</p></div></div><div className="vc-price"><small>FIRST CAMPAIGN</small><h3>$299</h3><p>Founding-customer launch package</p><ul><li><Check/> Target campaign setup</li><li><Check/> Up to 25 property concepts*</li><li><Check/> Personalized postcard creative</li><li><Check/> Unique QR project-page structure</li><li><Check/> Lead/response tracking setup</li><li><Check/> Campaign review before launch</li></ul><a className="button full" href={FOUNDING_PAYMENT_LINK}>Pay $299 — Start My Founding Campaign <ArrowRight size={18}/></a><small className="vc-note">*Final mailed quantity and any printing/postage/property-data costs are confirmed before campaign launch. No unapproved pass-through costs.</small></div></section>

  <section className="vc-final"><div className="wrap"><h2>Your next customer may already be driving past the project you could have sold them.</h2><p>Show the right homeowner what their property could become.</p><a className="button" href={FOUNDING_PAYMENT_LINK}>Start a Visual Canvasser Campaign <ArrowRight size={18}/></a></div></section>
 </main>
}
