'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, Home, Mail, QrCode, Search, Sparkles, Target, WandSparkles } from 'lucide-react';

const industries = ['Landscaping','Roofing','Pressure Washing','Exterior Painting','Fencing','Tree Service','Hardscaping','Outdoor Lighting'];
const examples: Record<string,string[]> = {
  Landscaping:['6 compact evergreen shrubs','3 flowering hydrangeas','Seasonal color','Fresh mulch + bed edging'],
  Roofing:['Architectural shingles','New ridge cap','Updated roof vents','Matching flashing'],
  'Pressure Washing':['Driveway surface cleaning','Front walk cleaning','Curb treatment','Entry concrete brightening'],
  'Exterior Painting':['Updated body color','Contrasting trim','Front-door accent','Exterior prep + coating'],
  Fencing:['Privacy fence concept','Matching gate','Post + rail layout','Property-line finish'],
  'Tree Service':['Canopy thinning','Dead-limb removal','Crown shaping','Debris cleanup'],
  Hardscaping:['Paver walkway','Defined border','Decorative gravel','Planting accents'],
  'Outdoor Lighting':['Path lights','Facade uplighting','Feature-tree lighting','Entry lighting'],
};

export default function VisualCanvasserSales(){
 const [industry,setIndustry]=useState('Landscaping');
 return <main className="vc-page">
  <nav className="nav"><Link className="brand" href="/"><span className="logo"><Sparkles size={18}/></span> Workforce<span>AI</span></Link><div className="navlinks"><a href="#how">How it works</a><a href="#example">Example</a><a href="#offer">Founding offer</a></div><Link className="button small" href="/founding">Get My First Campaign</Link></nav>
  <section className="vc-hero wrap"><div><div className="eyebrow">VISUAL CANVASSER FOR HOME-SERVICE BUSINESSES</div><h1>Don't just tell homeowners what you can do. <em>Show them.</em></h1><p className="lede">We help identify promising properties, create a personalized before-and-after project concept, and turn it into direct mail that sends the homeowner to a trackable estimate page.</p><div className="actions left-actions"><Link className="button" href="/founding">Become a Founding Customer <ArrowRight size={18}/></Link><a className="ghost" href="#example">See a campaign example</a></div><div className="proof vc-proof"><span><Check/> Personalized to the property</span><span><Check/> Built around your service</span><span><Check/> QR response tracking</span></div></div><div className="vc-mailer"><div className="vc-mail-photo"><span>AFTER CONCEPT</span><div>🏡</div><b>Imagine this at your home.</b></div><div className="vc-mail-copy"><small>CREATED FOR THIS PROPERTY</small><h3>We had an idea for your front yard.</h3><p>Scan to see the concept, what's included, and request an estimate.</p><div className="vc-qr"><QrCode size={56}/><span>YOUR<br/>PROJECT</span></div></div></div></section>

  <section id="how" className="section vc-soft"><div className="wrap"><div className="sectionhead"><span>FROM PROSPECT TO ESTIMATE</span><h2>A smarter version of neighborhood canvassing.</h2><p>Instead of sending the same advertisement to everyone, Visual Canvasser builds outreach around the property and the work you actually want to sell.</p></div><div className="vc-steps">{[[Search,'1','Target','Choose service areas and the kinds of jobs you want.'],[Home,'2','Visualize','Create a realistic before/after concept for the property.'],[WandSparkles,'3','Explain','Show the improvements, materials and project scope represented.'],[Mail,'4','Mail','Turn the concept into a personalized direct-mail piece.'],[QrCode,'5','Track','A unique QR page captures interest and estimate requests.'],[Target,'6','Follow up','Interested homeowners move into your sales workflow.']].map(([Icon,n,t,d]:any)=><article key={n}><span>{n}</span><Icon size={22}/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

  <section id="example" className="section wrap"><div className="sectionhead"><span>INTERACTIVE EXAMPLE</span><h2>One engine. Different home-service businesses.</h2><p>Choose a service to see the type of property-specific proposal the campaign could create.</p></div><div className="vc-tabs">{industries.map(x=><button key={x} onClick={()=>setIndustry(x)} className={industry===x?'active':''}>{x}</button>)}</div><div className="vc-demo"><div className="vc-before"><small>PROPERTY TODAY</small><div>🏠</div><b>Current property view</b><p>Authorized/current imagery is used when available. We do not represent unavailable property imagery as live.</p></div><div className="vc-arrow"><ArrowRight/></div><div className="vc-after"><small>{industry.toUpperCase()} CONCEPT</small><div>🏡</div><b>Realistic proposed improvement</b><ul>{examples[industry].map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul></div><div className="vc-scope"><small>WHAT THE HOMEOWNER SEES</small><h3>Your personalized project idea</h3><p>A concise explanation of the visible changes, plus a QR code to explore the project and request an estimate.</p><div className="vc-qr big"><QrCode size={70}/></div><Link className="button" href="/founding">Request My Campaign</Link></div></div></section>

  <section className="dark vc-difference"><div className="wrap split"><div><div className="tag">WHY THIS IS DIFFERENT</div><h2>Generic postcards advertise.<br/><em>This starts a conversation.</em></h2><p>The homeowner sees their property and a project idea made for them. When they scan, the business can know which campaign/property generated the response and continue the conversation.</p></div><div className="vc-stack"><div><b>1</b><span>Property-specific creative</span></div><div><b>2</b><span>Service-specific scope</span></div><div><b>3</b><span>Personalized QR destination</span></div><div><b>4</b><span>Lead capture + follow-up workflow</span></div></div></div></section>

  <section id="offer" className="section wrap vc-offer"><div><span className="eyebrow">FOUNDING CUSTOMER CAMPAIGN</span><h2>Be one of the first businesses we build this for.</h2><p>We're onboarding a small number of home-service businesses while we finish automating the complete workflow. Your first campaign is delivered as a managed service and helps shape the production product.</p><div className="vc-honesty"><b>What “founding customer” means</b><p>Some campaign steps may be completed with human-assisted AI while integrations are being finalized. We will not claim an external data source, supplier catalog, mailing integration, or property-image source is automated until it is actually connected and tested.</p></div></div><div className="vc-price"><small>FIRST CAMPAIGN</small><h3>$299</h3><p>Founding-customer launch package</p><ul><li><Check/> Target campaign setup</li><li><Check/> Up to 25 property concepts*</li><li><Check/> Personalized postcard creative</li><li><Check/> Unique QR project-page structure</li><li><Check/> Lead/response tracking setup</li><li><Check/> Campaign review before launch</li></ul><Link className="button full" href="/founding">Request My Founding Campaign <ArrowRight size={18}/></Link><small className="vc-note">*Final mailed quantity and any printing/postage/property-data costs are confirmed before campaign launch. No unapproved pass-through costs.</small></div></section>

  <section className="vc-final"><div className="wrap"><h2>Your next customer may already be driving past the project you could have sold them.</h2><p>Show the right homeowner what their property could become.</p><Link className="button" href="/founding">Start a Visual Canvasser Campaign <ArrowRight size={18}/></Link></div></section>
 </main>
}
