'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, CreditCard, Loader2, ShieldCheck, Sparkles } from 'lucide-react';

const plans=[
 {key:'starter',name:'Starter',price:99,desc:'For smaller service businesses',items:['150 voice minutes / month','Lead capture + summaries','Email lead notifications','Custom greeting & FAQs']},
 {key:'growth',name:'Growth',price:249,desc:'For businesses that rely on the phone for steady new jobs',items:['500 voice minutes / month','Advanced lead qualification','More custom call flows','Priority setup changes'],featured:true},
 {key:'pro',name:'Pro',price:499,desc:'For higher-volume teams',items:['1,200 voice minutes / month','Advanced routing logic','Multiple call experiences','Priority support']},
];

export default function CheckoutPage(){
 const [loading,setLoading]=useState(''); const [error,setError]=useState('');
 async function buy(plan:string){
  setLoading(plan);setError('');
  try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})});const d=await r.json();if(!r.ok||!d.url)throw new Error(d.error||'Checkout could not start.');window.location.href=d.url}catch(e:any){setError(e.message||'Checkout could not start.');setLoading('')}
 }
 return <main className="checkout-page"><nav><Link href="/receptionist-demo"><ArrowLeft/> Back to Ava</Link><b><Sparkles/> Workforce AI</b></nav><section className="checkout-head"><span>START YOUR AI RECEPTIONIST</span><h1>Choose the coverage that fits your business.</h1><p>Every plan includes our $299 one-time Founding Setup. We configure Ava with you, customize the voice and call flow, test her, and help get her ready for customers.</p></section><section className="checkout-plans">{plans.map(p=><article className={p.featured?'featured':''} key={p.key}>{p.featured&&<i>MOST POPULAR</i>}<h2>{p.name}</h2><p>{p.desc}</p><div><strong>${p.price}</strong><span>/month</span></div><small>+ $299 one-time setup</small><ul>{p.items.map(x=><li key={x}><Check/>{x}</li>)}</ul><button onClick={()=>buy(p.key)} disabled={!!loading}>{loading===p.key?<><Loader2 className="spin"/> Opening secure checkout...</>:<>Choose {p.name} <CreditCard/></>}</button></article>)}</section>{error&&<p className="checkout-error">{error}</p>}<section className="checkout-trust"><span><ShieldCheck/> Secure payment through Stripe</span><span><Check/> We help configure Ava</span><span><Check/> Voice & call-flow customization</span></section><style jsx>{`
.checkout-page{min-height:100vh;background:#07110c;color:#f5f8f5;font-family:Inter,system-ui,sans-serif;padding-bottom:70px}.checkout-page nav{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 max(20px,calc((100vw - 1080px)/2));border-bottom:1px solid #173126}.checkout-page nav a,.checkout-page nav b{display:flex;gap:8px;align-items:center;color:inherit;text-decoration:none;font-size:13px}.checkout-page nav svg{width:17px}.checkout-head{max-width:760px;margin:75px auto 45px;text-align:center;padding:0 20px}.checkout-head>span{font-size:10px;letter-spacing:.14em;font-weight:900;color:#8fe66f}.checkout-head h1{font:600 clamp(42px,5vw,65px)/1.02 Georgia,serif;letter-spacing:-.035em;margin:15px 0}.checkout-head p{color:#9eaaa2;line-height:1.65}.checkout-plans{width:min(1080px,calc(100% - 40px));margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.checkout-plans article{border:1px solid #2b4837;background:#0c1a12;border-radius:16px;padding:28px;position:relative}.checkout-plans article.featured{border-color:#8fe66f;box-shadow:0 0 0 1px #8fe66f}.checkout-plans i{position:absolute;top:-11px;left:50%;transform:translateX(-50%);background:#8fe66f;color:#07110c;font-style:normal;font-size:8px;font-weight:900;padding:5px 10px;border-radius:99px}.checkout-plans h2{font:600 28px Georgia,serif;margin:3px 0 8px}.checkout-plans article>p{color:#85938a;font-size:12px;min-height:48px}.checkout-plans article>div{display:flex;align-items:end;gap:5px;margin-top:18px}.checkout-plans strong{font:600 48px Georgia,serif}.checkout-plans article>div span{color:#87958b;padding-bottom:7px}.checkout-plans small{color:#8fe66f}.checkout-plans ul{list-style:none;padding:20px 0;min-height:175px;display:grid;gap:9px}.checkout-plans li{display:flex;gap:7px;align-items:flex-start;color:#c7d0ca;font-size:11px}.checkout-plans li svg{width:15px;color:#8fe66f}.checkout-plans button{width:100%;border:1px solid #8fe66f;background:#8fe66f;color:#07110c;border-radius:9px;padding:13px;display:flex;justify-content:center;align-items:center;gap:8px;font-weight:850;cursor:pointer}.checkout-plans button svg{width:17px}.checkout-plans button:disabled{opacity:.65}.checkout-error{text-align:center;color:#ff8e8e;margin:20px}.checkout-trust{display:flex;justify-content:center;gap:24px;flex-wrap:wrap;color:#839087;font-size:11px;margin:30px 20px}.checkout-trust span{display:flex;gap:6px;align-items:center}.checkout-trust svg{width:15px;color:#8fe66f}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:800px){.checkout-plans{grid-template-columns:1fr}.checkout-head{margin-top:50px}}
`}</style></main>
}
